name: easy_search_bar
description: AppBar with animated search functionality that can be used as regular or floating AppBar
version: 3.0.0
homepage: https://github.com/esaiaswestberg/flutter_easy_search_bar

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
